title: Nadia Ríos
logo: '<img src="/Images/NR.jpg" alt="Nadia Ríos" style="border-radius: 50%; width: 150px; height: 150px; object-fit: cover;">'
#descriotion: 
#show_downloads
theme: jekyll-theme-minimal
